### PR TITLE
test suite defined by tests.csv

### PR DESCRIPTION
**Pull request by jmacxx**
Per https://github.com/jb55/btcs/issues/24 implemented the test suite using a csv file same way as you did in bcalc.  Added more tests.  test.c not needed any more.

### CODE REVIEW

**Comment by jmacxx** [comment]
Currently failing tests refer to https://github.com/jb55/btcs/issues/41

    $ make check
    1..23
    ok 1 - test_simple
    ok 2 - test_nip
    ok 3 - test_2dup_not_enough_input
    ok 4 - negative_integer
    ok 5 - add_negative_two
    ok 6 - big_int_serializes_ok
    ok 7 - test_small_int
    ok 8 - test_OP_1ADD
    ok 9 - test_OP_1SUB
    ok 10 - test_OP_NEGATE
    ok 11 - test_OP_NEGATE_negative
    ok 12 - test_OP_ABS
    ok 13 - test_OP_ABS_negative
    ok 14 - sub_negative_two
    ok 15 - test_OP_DROP
    ok 16 - test_OP_NOT_0
    not ok 17 - test_OP_NOT_1
    #
    #    got 'script      1 OP_NOT script_hex  5191 stack       0 stack_hex    results     success', expected 'script      1 OP_NOT script_hex  5191 stack       0 stack_hex   00 results     success'
    #
    not ok 18 - test_OP_NOT_2
    #
    #    got 'script      2 OP_NOT script_hex  5291 stack       0 stack_hex    results     success', expected 'script      2 OP_NOT script_hex  5291 stack       0 stack_hex   00 results     success'
    #
    not ok 19 - test_OP_0NOTEQUAL0
    #
    #    got 'script      0 OP_0NOTEQUAL script_hex  0092 stack       0 stack_hex    results     success', expected 'script      0 OP_0NOTEQUAL script_hex  0092 stack       0 stack_hex   00 results     success'
    #
    ok 20 - test_OP_0NOTEQUAL2
    ok 21 - test_ADD_SUB
    ok 22 - test_BOOLAND
    not ok 23 - test_BOOLAND
    #
    #    got 'script      0 0 OP_BOOLAND script_hex  00009a stack       0 stack_hex    results     success', expected 'script      0 0 OP_BOOLAND script_hex  00009a stack       0 stack_hex   00 results     success'
    #

**Comment by jb55** [comment]
looks awesome! perhaps the `expected` line could go under the `got` for comparison?
```
#
#    got      'script      1 OP_NOT script_hex  5191 stack       0 stack_hex    results     success', 
#    expected 'script      1 OP_NOT script_hex  5191 stack       0 stack_hex   00 results     success'
#
```

**Comment by jmacxx** [comment]
:+1: done, looks cleaner that way.

**Comment by jb55** [comment]
thanks!

**Pull request closed without merging**
